[package]
name = "dialog_overlay"
description = "An example of using neutron-components to create a Dialog with overlay."
version = "0.5.1"
rust-version = "1.95.0"
publish = false
edition.workspace = true

[dependencies]
anyhow.workspace = true
gpui.workspace = true
gpui_platform.workspace = true
neutron-components.workspace = true
neutron-components-assets.workspace = true

[lints]
workspace = true
