[package]
name = "gpui-wry"
description = "WebView support for GPUI, based on Wry."
keywords = ["webview", "gpui","wry"]
license = "Apache-2.0"
documentation = "https://docs.rs/neutron-components"
homepage = "https://github.com/BumpyClock/neutron"
repository = "https://github.com/BumpyClock/neutron/tree/main/framework/crates/webview"
readme = "README.md"
edition.workspace = true
publish = true
version = "0.7.0"
rust-version = "1.95.0"

[features]
inspector = ["wry/devtools"]

[lib]
doctest = false

[dependencies]
anyhow.workspace = true
gpui.workspace = true
wry = { version = "0.53.3", package = "lb-wry" }
